// Package golangintro contains lightweight course notes.
//
// 2) 測試與品質（1～3 天）
//
// 常用指令：
//   go test ./...
//   go test -race ./...
//   go test -bench=. ./...
//   go vet ./...
//
// 範例測試檔：examples/go_basics/main_test.go
package golangintro
